"""Pure protobuf<->Pydantic conversion between MesherraEnvelope and A2A Message.

Per ARCHITECTURE.md §13.10. This module is the *only* place protobuf wire
types and Mesherra's Pydantic envelope meet. Both conversion functions are
pure (no I/O, no logging, no global state) and round-trip:

    envelope_to_a2a_message(env)             -> a2a.types.Message
    a2a_message_to_envelope(msg)             -> MesherraEnvelope

    a2a_message_to_envelope(
        envelope_to_a2a_message(env)
    ) == env       # for every well-formed envelope

The mapping follows the table in ARCHITECTURE.md §13.10:

    envelope.task_id              -> Message.task_id
    envelope.context_id           -> Message.context_id
    envelope.payload (dict)       -> Message.parts[0].data (Value(struct_value=Struct))
    envelope.payload_schema       -> Message.metadata["mesherra.send_claim.payload_schema"]
    envelope.sender_principal_id  -> Message.metadata["mesherra.send_claim.sender_principal_id"]
    envelope.timestamp            -> Message.metadata["mesherra.send_claim.timestamp"]
    envelope.send_claim_signature -> Message.metadata["mesherra.send_claim.signature"]
    (implicit)                    -> Message.role = ROLE_AGENT

The signature on the wire is over a :class:`mesherra.models.primitives.SendClaim`,
not over a full Residue. See ARCHITECTURE.md §13.10 for the rationale.

Numeric precision note: protobuf's ``google.protobuf.Value`` represents all
numbers as ``double`` (float64). For Phase 1 payloads (small integers and
strings) this is invisible — JCS canonicalizes ``int 30`` and ``float 30.0``
to the same bytes (verified). Phase 2+ payloads that need integer precision
beyond 2^53 must encode large integers as strings before placing them in
the envelope.

Strict isolation: ``a2a.types`` imports are confined to this ``a2a_adapter``
package — ``wire.py`` for the pure conversion functions, ``adapter.py`` for
the Client / HTTP-server lifecycle. No module outside this directory imports
``a2a.types``. Callers receive ``MesherraEnvelope`` and pass ``MesherraEnvelope``;
the protobuf shape never leaks. The isolation is mechanically enforced by
``tests/unit/test_a2a_isolation.py``.
"""

from __future__ import annotations

from typing import Any

from a2a.types import Message, Part, Role
from google.protobuf import struct_pb2
from google.protobuf.json_format import MessageToDict, ParseDict

from mesherra.models.primitives import Operation

from .envelope import MesherraEnvelope

# Reserved metadata key namespace. The `mesherra.*` prefix is reserved by
# Mesherra; consumers MUST NOT use this prefix for their own metadata.
# All five SendClaim fields share the `mesherra.send_claim.*` prefix so the
# wire layout mirrors the SendClaim model exactly. This consistency is
# load-bearing: when a step-5 implementer reads the spec, they shouldn't have
# to remember which fields live under .send_claim vs .provenance vs .principal.
# `operation` joined the SendClaim in Phase 1 review (see ARCHITECTURE.md
# §13.10): a MitM that flipped proposal↔acceptance under the old wire layout
# could coerce one party into appearing to agree to a proposal they only
# acknowledged. Signing it closes that gap.
_KEY_PAYLOAD_SCHEMA = "mesherra.send_claim.payload_schema"
_KEY_SENDER_PRINCIPAL_ID = "mesherra.send_claim.sender_principal_id"
_KEY_TIMESTAMP = "mesherra.send_claim.timestamp"
_KEY_SIGNATURE = "mesherra.send_claim.signature"
_KEY_OPERATION = "mesherra.send_claim.operation"

_REQUIRED_METADATA_KEYS = frozenset(
    {
        _KEY_PAYLOAD_SCHEMA,
        _KEY_SENDER_PRINCIPAL_ID,
        _KEY_TIMESTAMP,
        _KEY_SIGNATURE,
        _KEY_OPERATION,
    }
)


class WireFormatError(ValueError):
    """An inbound A2A Message could not be parsed into a MesherraEnvelope.

    Raised by :func:`a2a_message_to_envelope` when the message is malformed
    or missing required Mesherra-namespaced metadata. The Inbound Gateway
    (§13.3) maps this to an A2A ``InvalidParamsError`` response.
    """


def envelope_to_a2a_message(
    envelope: MesherraEnvelope, *, message_id: str
) -> Message:
    """Translate a Mesherra envelope into an A2A protobuf Message.

    ``message_id`` is the A2A message identifier (one per send); typically a
    fresh UUID generated by the adapter at send time. It does NOT correspond
    to any Mesherra concept — the Mesherra "this is the same exchange" link
    is the ``task_id`` / ``context_id`` pair.

    The returned Message is ready to hand to ``a2a.client.Client.send_message``.
    """
    payload_value = _dict_to_value(envelope.payload)
    metadata_struct = _build_metadata(
        schema=envelope.payload_schema,
        principal_id=envelope.sender_principal_id,
        send_claim_timestamp=envelope.timestamp,
        send_claim_signature=envelope.send_claim_signature,
        operation=envelope.operation.value,
    )
    return Message(
        message_id=message_id,
        context_id=envelope.context_id,
        task_id=envelope.task_id,
        role=Role.ROLE_AGENT,
        parts=[Part(data=payload_value)],
        metadata=metadata_struct,
    )


def a2a_message_to_envelope(message: Message) -> MesherraEnvelope:
    """Translate an inbound A2A Message back into a Mesherra envelope.

    Raises :class:`WireFormatError` if the message is missing any
    Mesherra-namespaced metadata key or its first Part does not carry a
    structured payload. Schema-level validation of the payload itself is
    NOT performed here; that is the Inbound Gateway's job (§13.3 step 1).
    Signature verification is also NOT performed here; that is §13.3 step 3.
    """
    if not message.parts:
        raise WireFormatError("Message has no Parts; expected payload in parts[0].data")

    first_part = message.parts[0]
    if not first_part.HasField("data"):
        raise WireFormatError(
            "Message.parts[0] does not carry .data; Mesherra envelopes require "
            "the payload as a structured Part.data (google.protobuf.Value)"
        )

    payload = _value_to_dict(first_part.data)

    metadata = _struct_to_dict(message.metadata) if message.HasField("metadata") else {}
    missing = _REQUIRED_METADATA_KEYS - set(metadata.keys())
    if missing:
        raise WireFormatError(
            "Message.metadata is missing required Mesherra keys: "
            f"{sorted(missing)}"
        )

    return MesherraEnvelope(
        task_id=message.task_id,
        context_id=message.context_id,
        sender_principal_id=metadata[_KEY_SENDER_PRINCIPAL_ID],
        payload=payload,
        payload_schema=metadata[_KEY_PAYLOAD_SCHEMA],
        operation=Operation(metadata[_KEY_OPERATION]),
        timestamp=metadata[_KEY_TIMESTAMP],
        send_claim_signature=metadata[_KEY_SIGNATURE],
    )


# -- internals ------------------------------------------------------------


def _build_metadata(
    *,
    schema: str,
    principal_id: str,
    send_claim_timestamp: str,
    send_claim_signature: str,
    operation: str,
) -> struct_pb2.Struct:
    md = struct_pb2.Struct()
    ParseDict(
        {
            _KEY_PAYLOAD_SCHEMA: schema,
            _KEY_SENDER_PRINCIPAL_ID: principal_id,
            _KEY_TIMESTAMP: send_claim_timestamp,
            _KEY_SIGNATURE: send_claim_signature,
            _KEY_OPERATION: operation,
        },
        md,
    )
    return md


def _dict_to_value(d: dict[str, Any]) -> struct_pb2.Value:
    """Wrap a dict as a protobuf Value (whose ``struct_value`` is a Struct).

    Part.data expects a Value, which is a wrapper around one of: null, bool,
    number, string, struct, list. For Mesherra payloads we always use struct.
    """
    s = struct_pb2.Struct()
    ParseDict(d, s)
    return struct_pb2.Value(struct_value=s)


def _value_to_dict(value: struct_pb2.Value) -> dict[str, Any]:
    """Unwrap a protobuf Value carrying a Struct into a Python dict.

    Raises WireFormatError if the Value does not carry a struct (Mesherra
    payloads are always dicts at the top level).
    """
    if not value.HasField("struct_value"):
        raise WireFormatError(
            "Part.data Value does not carry a struct_value; Mesherra payloads "
            "must be JSON objects (dicts) at the top level"
        )
    return _struct_to_dict(value.struct_value)


def _struct_to_dict(s: struct_pb2.Struct) -> dict[str, Any]:
    return MessageToDict(s, preserving_proto_field_name=True)
